site_name: 高性能计算导论实验文档
site_description: 'Documentation for Labs of Introduction to High Performance Computing'
site_author: 'HPC Lab Developers'
copyright: 'Copyright &copy; 2021 Department of Computer Science and Technology, Tsinghua University. All Rights Reserved.'

theme: 
  name: 'material'
  language: 'zh'
  custom_dir: 'theme-override/'
  icon:
    logo: material/memory
    repo: fontawesome/brands/github
  features:
    # - navigation.tabs
    # - navigation.instant

repo_name: 'thu-cs-lab/HPC-Lab-Docs'
repo_url: 'https://github.com/thu-cs-lab/HPC-Lab-Docs'

extra:
  pagetime: 'on'

nav:
  - 总述: index.md
  - 集群使用: cluster.md
  - 工具说明: tools.md
  - 实验说明:
    - 实验零: exp/0.aplusb.md
    # - 实验一: exp/1.odd_even_sort.md
    # - 实验二: exp/2.bfs.md
    # - 实验三: exp/3.mssp.md
    # - 附加实验: exp/4.spmm.md
  - 参考资料: reference.md
  # - FAQ: faq.md

extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
  - git-authors:
      show_contribution: true
      show_line_count: true

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - def_list
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

